// Définit une map de couleurs pour les notifications Slack selon le statut du pipeline
def COLOR_MAP = [
 'SUCCESS': 'good', // vert dans slack
 'FAILURE': 'danger', // rouge dans slack
]

pipeline {
  agent any // Utilise n'importe quel agent disponible

  environment {
    SLACK_CHANNEL = '#jenkins-cicd' // Channel Slack pour les notifications
    CLUSTER = 'vprofile-prod-cluster' // Nom du cluster ECS
    SERVICE = 'vpro-app-cluster-prod-svc' // Nom du service du cluster ECS
  }

  stages {
    stage('Deploy to ECS Production') {
      steps {
        withAWS(credentials: 'AwsCredentials', region: 'eu-west-3') {
          sh 'aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE} --force-new-deployment'
        }
      }
    }
  }

  // Envoie des notifications Slack après l'exécution du pipeline
  post {
    always {
      echo 'Slack Notifications'
      slackSend channel: "${SLACK_CHANNEL}",
        color: COLOR_MAP[currentBuild.currentResult],
        message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
    }
  }
}
